/**
 * Configuration for the Trip Planner.
 *
 * GENERATED by scripts/generate-env.mjs from environment variables — do not
 * edit by hand; your changes will be overwritten on the next build/serve.
 *
 * Two layers, runtime wins over build-time:
 *  - Build-time defaults, baked here from the DEFAULT_DEPARTURE_TZ /
 *    DEFAULT_TRIP_TZ / STORAGE_BACKEND / API_BASE_URL env vars at build time
 *    (used by `npm start` and the GitHub Pages deploy).
 *  - Runtime overrides via the global `window.__TRIP_PLANNER_ENV__`, loaded
 *    from `/config.js` before the app bundle. The Docker image writes that file
 *    from container env vars on startup, so one image is reconfigurable per
 *    deployment without a rebuild.
 */
const runtime: any =
  (typeof globalThis !== 'undefined' &&
    (globalThis as any).__TRIP_PLANNER_ENV__) ||
  {};

const backend =
  runtime.storageBackend === 'http' || runtime.storageBackend === 'indexeddb'
    ? runtime.storageBackend
    : "http";

export const environment = {
  /** Default departure (home) zone for a new trip. Empty = use device zone. */
  defaultDepartureTimeZone:
    runtime.defaultDepartureTimeZone ?? "",
  /** Default destination zone for a new trip. */
  defaultTripTimeZone: runtime.defaultTripTimeZone || "Asia/Tokyo",
  /** Persistence backend: "indexeddb" (browser-local) or "http" (FastAPI). */
  storageBackend: backend,
  /** Base URL of the backend API when storageBackend === "http". */
  apiBaseUrl: runtime.apiBaseUrl || "http://127.0.0.1:8000",
};
