/**
 * Build-time configuration for the Trip Planner.
 *
 * GENERATED by scripts/generate-env.mjs from environment variables — do not
 * edit by hand; your changes will be overwritten on the next build/serve.
 * Override per-build with the DEFAULT_DEPARTURE_TZ / DEFAULT_TRIP_TZ env vars.
 */
export const environment = {
  /** Default departure (home) zone for a new trip. Empty = use device zone. */
  defaultDepartureTimeZone: "",
  /** Default destination zone for a new trip. */
  defaultTripTimeZone: "Asia/Tokyo",
};
