/**
 * Generates src/environments/environment.ts from environment variables so the
 * Trip Planner's defaults are configurable per build/serve.
 *
 *   DEFAULT_DEPARTURE_TZ  Default departure (home) zone for a new trip.
 *                         Empty (the default) falls back to the device zone.
 *   DEFAULT_TRIP_TZ       Default destination zone for a new trip.
 *                         Defaults to "Asia/Tokyo".
 *
 * Run automatically via the npm `prestart` / `prebuild` hooks.
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const target = join(root, 'src', 'environments', 'environment.ts');

const departure = process.env.DEFAULT_DEPARTURE_TZ ?? '';
const trip = process.env.DEFAULT_TRIP_TZ || 'Asia/Tokyo';

const literal = (value) => JSON.stringify(value);

const contents = `/**
 * Build-time configuration for the Trip Planner.
 *
 * GENERATED by scripts/generate-env.mjs from environment variables — do not
 * edit by hand; your changes will be overwritten on the next build/serve.
 * Override per-build with the DEFAULT_DEPARTURE_TZ / DEFAULT_TRIP_TZ env vars.
 */
export const environment = {
  /** Default departure (home) zone for a new trip. Empty = use device zone. */
  defaultDepartureTimeZone: ${literal(departure)},
  /** Default destination zone for a new trip. */
  defaultTripTimeZone: ${literal(trip)},
};
`;

mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, contents);

console.log(
  `[generate-env] departure="${departure || '(device zone)'}" trip="${trip}"`,
);
