/**
 * Generates src/environments/environment.ts from environment variables so the
 * Trip Planner's defaults are configurable per build/serve.
 *
 *   DEFAULT_DEPARTURE_TZ  Default departure (home) zone for a new trip.
 *                         Empty (the default) falls back to the device zone.
 *   DEFAULT_TRIP_TZ       Default destination zone for a new trip.
 *                         Defaults to "Asia/Tokyo".
 *   STORAGE_BACKEND       Where trips are persisted: "indexeddb" (default,
 *                         browser-local) or "http" (FastAPI/Postgres backend).
 *   API_BASE_URL          Base URL of the backend when STORAGE_BACKEND="http".
 *                         Defaults to "http://localhost:8000".
 *
 * These can be set on the command line (e.g. `STORAGE_BACKEND=http npm start`)
 * or placed in a `.env` file at the repo root (see `.env.example`). Variables
 * already present in the environment take precedence over the `.env` file.
 *
 * Run automatically via the npm `prestart` / `prebuild` hooks.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const target = join(root, 'src', 'environments', 'environment.ts');

/**
 * Load KEY=VALUE pairs from a `.env` file into process.env without overriding
 * variables that are already set (so shell / CLI values win). Minimal parser:
 * skips blank lines and `#` comments, strips matching surrounding quotes.
 */
function loadDotEnv(path) {
  let text;
  try {
    text = readFileSync(path, 'utf8');
  } catch {
    return; // no .env file — that's fine
  }
  for (const line of text.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    if (!key || key in process.env) continue;
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    process.env[key] = value;
  }
}

loadDotEnv(join(root, '.env'));

const departure = process.env.DEFAULT_DEPARTURE_TZ ?? '';
const trip = process.env.DEFAULT_TRIP_TZ || 'Asia/Tokyo';
const storageBackend =
  process.env.STORAGE_BACKEND === 'http' ? 'http' : 'indexeddb';
const apiBaseUrl = process.env.API_BASE_URL || 'http://localhost:8000';

const literal = (value) => JSON.stringify(value);

const contents = `/**
 * Build-time configuration for the Trip Planner.
 *
 * GENERATED by scripts/generate-env.mjs from environment variables — do not
 * edit by hand; your changes will be overwritten on the next build/serve.
 * Override per-build with the DEFAULT_DEPARTURE_TZ / DEFAULT_TRIP_TZ /
 * STORAGE_BACKEND / API_BASE_URL env vars.
 */
export const environment = {
  /** Default departure (home) zone for a new trip. Empty = use device zone. */
  defaultDepartureTimeZone: ${literal(departure)},
  /** Default destination zone for a new trip. */
  defaultTripTimeZone: ${literal(trip)},
  /** Persistence backend: "indexeddb" (browser-local) or "http" (FastAPI). */
  storageBackend: ${literal(storageBackend)},
  /** Base URL of the backend API when storageBackend === "http". */
  apiBaseUrl: ${literal(apiBaseUrl)},
};
`;

mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, contents);

console.log(
  `[generate-env] departure="${departure || '(device zone)'}" trip="${trip}" ` +
    `backend="${storageBackend}"${storageBackend === 'http' ? ` api="${apiBaseUrl}"` : ''}`,
);
